#
# more information can be found here http://sonata-project.org/bundles/page
#
sonata_seo:
    encoding:             UTF-8
    page:
        default:          sonata.seo.page.default
        title:            Koty Syberyjskie - hodowla "Sen Diany"
        metas:
            name:
                keywords:             kot, syberyjski, sen diany
                description:          Strona internetowa hodowli kotów syberyjskich "Sen Diany"
                robots:               index, follow

            property:
                'og:site_name':       Koty Syberyjskie - hodowla "Sen Diany"
                'og:description':     Strona internetowa hodowli kotów syberyjskich "Sen Diany"

            http-equiv:
                'Content-Type':         text/html; charset=utf-8
                #'X-Ua-Compatible':      IE=EmulateIE7

        head:
            'xmlns':              ''
            'xmlns:og':           http://opengraphprotocol.org/schema/

    sitemap:
        doctrine_orm:
            # media
            - { connection: doctrine.dbal.default_connection, route: sonata_media_view, parameters: {id: null}, query: "SELECT id, updated_at as lastmod, 'weekly' as changefreq, '0.5' as prioriy FROM media__media WHERE enabled = true" }
            # blog post
            - { connection: doctrine.dbal.default_connection, route: sonata_news_view, parameters: {permalink: null}, query: "SELECT CONCAT_WS('/', YEAR(created_at), MONTH(created_at), DAY(created_at), slug) as permalink , updated_at as lastmod, 'weekly' as changefreq, '0.5' as prioriy FROM news__post WHERE enabled = 1 AND (publication_date_start IS NULL OR publication_date_start <= NOW())" }
